# If this is true the main loop will exit after sending the errors to the
# handlers
exitOnError = true

# The user agent that will be presented to reddit
userAgent = "<platform>:<app ID>:<version string> (by /u/<reddit username>)"

# A list of subreddits to subscribe to. This list is from
# http://redditlist.com and represents the subreddits with the most growth
# on Wed Mar 23 2:22 AM
subreddits = [
  "AskReddit",
  "The_Donald",
  "politics",
  "funny",
  "worldnews",
  "pics",
  "AdviceAnimals",
  "videos",
  "nba",
  "todayilearned",
  "gifs",
  "news",
  "leagueoflegends",
  "SandersForPresident",
  "gaming",
  "relationships",
  "nfl",
  "WTF",
  "BlackPeopleTwitter",
  "soccer",
  "aww",
  "movies",
  "SquaredCircle",
  "hearthstone",
  "thedivision",
  "thewalkingdead",
  "IAmA",
  "GlobalOffensive",
  "hockey",
  "Showerthoughts",
  "me_irl",
  "pcmasterrace",
  "DotA2",
  "technology",
  "television",
  "MMA",
  "CollegeBasketball",
  "4chan",
  "rupaulsdragrace",
  "magicTCG",
  "mildlyinteresting",
  "europe",
  "h3h3productions",
  "TumblrInAction",
  "Games",
  "hiphopheads",
  "explainlikeimfive",
  "PoliticalDiscussion",
  "AskMen",
  "anime",
  "TrollXChromosomes",
  "nottheonion",
  "Music",
  "Jokes",
  "trees",
  "KotakuInAction",
  "apple",
  "Defenders",
  "CringeAnarchy",
  "oculus",
  "canada",
  "interestingasfuck",
  "Android",
  "heroesofthestorm",
  "cringepics",
  "atheism",
  "science",
  "tifu",
  "smashbros",
  "Fitness",
  "woahdude",
  "photoshopbattles",
  "european",
  "HighQualityGifs",
  "StarWars",
  "Celebs",
  "formula1",
  "Fallout",
  "wow",
  "legaladvice",
  "baseball",
  "pokemon",
  "StardewValley",
  "SubredditDrama",
  "Unexpected",
  "reactiongifs",
  "history",
  "personalfinance",
  "LifeProTips",
  "fo4",
  "books",
  "streetwear",
  "australia",
  "unitedkingdom",
  "CFB",
  "space",
  "fatlogic",
  "DestinyTheGame",
  "gentlemanboners",
  "Futurology",
  "2007scape",
  "TwoXChromosomes",
  "hillaryclinton",
  "xboxone",
  "sports",
  "RocketLeague",
  "halo",
  "Undertale",
  "asoiaf",
  "childfree",
  "bestof",
  "conspiracy",
  "askscience",
  "Kappa",
  "tf2",
  "youtubehaiku",
  "cringe",
  "sweden",
  "pathofexile",
  "RWBY",
  "cars",
  "betterCallSaul",
  "OutOfTheLoop",
  "OldSchoolCool",
  "PS4",
  "AskReddit",
  "funny",
  "todayilearned",
  "pics",
  "science",
  "worldnews",
  "IAmA",
  "announcements",
  "videos",
  "gaming",
  "movies",
  "Music",
  "aww",
  "news",
  "gifs",
  "askscience",
  "explainlikeimfive",
  "EarthPorn",
  "books",
  "television",
  "LifeProTips",
  "mildlyinteresting",
  "sports",
  "DIY",
  "Showerthoughts",
  "space",
  "Fitness",
  "tifu",
  "Jokes",
  "InternetIsBeautiful",
  "food",
  "photoshopbattles",
  "history",
  "gadgets",
  "nottheonion",
  "dataisbeautiful",
  "Futurology",
  "GetMotivated",
  "Documentaries",
  "personalfinance",
  "listentothis",
  "philosophy",
  "UpliftingNews",
  "OldSchoolCool",
  "Art",
  "nosleep",
  "creepy",
  "WritingPrompts",
  "technology",
  "TwoXChromosomes",
  "bestof",
  "WTF",
  "AdviceAnimals",
  "politics",
  "atheism",
  "woahdude",
  "leagueoflegends",
  "trees",
  "4chan",
  "Games",
  "europe",
  "programming",
  "interestingasfuck",
  "Android",
  "sex",
  "BlackPeopleTwitter",
  "cringepics",
  "gameofthrones",
  "reactiongifs",
  "malefashionadvice",
  "fffffffuuuuuuuuuuuu",
  "pcmasterrace",
  "Frugal",
  "YouShouldKnow",
  "HistoryPorn",
  "pokemon",
  "Unexpected",
  "AskHistorians",
  "lifehacks",
  "nfl",
  "StarWars",
  "relationships",
  "tattoos",
  "oddlysatisfying",
  "Minecraft",
  "comics",
  "JusticePorn",
  "soccer",
  "FoodPorn",
  "facepalm",
  "cringe",
  "OutOfTheLoop",
  "wheredidthesodago",
  "hiphopheads",
  "wallpapers",
  "gentlemanboners",
  "me_irl",
  "nba",
  "freebies",
  "GameDeals",
  "GlobalOffensive",
  "anime",
  "conspiracy",
  "buildapc",
  "TrueReddit",
  "Cooking",
  "hearthstone",
  "humor",
  "cats",
  "Fallout",
  "shittyaskscience",
  "loseit",
  "skyrim",
  "talesfromtechsupport",
  "baconreader",
  "apple",
  "offbeat",
  "spaceporn",
  "geek",
  "NetflixBestOf",
  "AbandonedPorn",
  "RoomPorn",
  "EatCheapAndHealthy",
  "MakeupAddiction",
  "mildlyinfuriating",
  "BannedFromThe_Donald",
  "stellarisgame",
  "SandersMedia",
  "assholedesign",
  "TheBarbarianClan",
  "RealTrueScienceFacts",
  "ProductTesting",
  "NorthAmerican",
  "Trunks",
  "PokkenGame",
  "PSVR",
  "DarkSouls3JPN",
  "bitsoup",
  "mlem",
  "jag_ivl",
  "TheChurchOfRogers",
  "ScaringChildren",
  "Ice_Poseidon",
  "EASPORTSUFC2",
  "LeafyIsHere",
  "european",
  "Flaked",
  "Vue",
  "PlanetCoaster",
  "CWArrow",
  "FootballCoach",
  "UneasyAlliance",
  "BirdsForScale",
  "zootopia",
  "paragon",
  "PeopleFuckingDying",
  "MarvelAvengersAcademy",
  "TurtleFacts",
  "saltandsanctuary",
  "NeverTrump",
  "GTAV_Cruises",
  "Lollapalooza",
  "The_Division",
  "hamiltonmusical",
  "Produce101",
  "VinylHBO",
  "Division",
  "Daredevil",
  "pyrocynical",
  "The_Donald",
  "SocialismVCapitalism",
  "ClashRoyale",
  "tommync2010",
  "Kossacks_for_Sanders",
  "AgainstHateSubreddits",
  "GalaxyS7",
  "thedivision",
  "LtCorbis",
  "TACN",
  "GreatXboxDeals",
  "TheBarons",
  "araragigirls",
  "TheSilphRoad",
  "StardewValley",
  "DC_Cinematic",
  "playstationvr",
  "traaaaaaannnnnnnnnns",
  "BestOfReports",
  "112263Hulu",
  "totallynotrobots",
  "survivetheculling",
  "DCEUleaks",
  "lgg5",
  "unexpectedhogwarts",
  "horaceandpete",
  "highrollersdnd",
  "AskTrumpSupporters",
  "transgendercirclejerk",
  "worldroleplay",
  "lucifer",
  "TrumpCalifornia",
  "h3h3productions",
  "samharris",
  "Defenders",
  "Pizza",
  "TheAdventureZone",
  "FUTMobile",
  "Sneks",
  "EASportsUFC",
  "gridcoin",
  "TedCruzForPresident",
  "enoughsandersspam",
  "DataHoarder",
  "dontdeadopeninside",
  "Billions",
  "faeria",
  "miraculousladybug",
  "BrasildoB",
  "CadenMoranDairy",
  "UMF",
  "DarkSouls3_ja",
  "boostedboards",
  "evilbuildings",
  "COMPLETEANARCHY",
  "RobinHood",
  "Megumin",
  "factorio",
  "trippinthroughtime",
  "NintendoNX",
  "hottiesfortrump",
  "darksouls3",
  "qualitynews",
  "JUSTNOFAMILY",
  "facebookdrama",
  "DearNetflix",
  "cosplaybutts",
  "thepunisher",
  "FreeGameFindings",
  "trollbi",
  "FreeCodeCamp",
  "Storyshift",
  "SCfitness",
  "shitpostemblem",
  "ELTP",
  "BattleRite",
  "KnightsOfPineapple",
  "haikyuu",
  "GifRecipes",
  "socialanarchism",
  "iamverybadass",
]

# All tags should be single words with no punctuation
# Global tags are looked for in every single post regardless of subreddit
globalAlertTags = [
  "globalTag",
]

# Subreddit tags are applied for each post in an individual subreddit
[subredditAlertTags]
  AskReddit = [
    "programming",
    "exampleTag",
  ]

# Reddit says you should not be making more than 60 requests per minute
[throttling]
  concurrentRequests = 10
  monitorFrequency = 5
